### ISSUE TITLE
iOS Example: Tapping "Reset" button results in another bunch of annotations added to the map without clearing the old ones.

### ISSUE THREAD

**Issue by grigorye** [choefele/CCHMapClusterController#58] opened 2014-10-27 15:04 UTC
Tapping "Reset" button results in another bunch of annotations added to the map without clearing the old ones.

Steps to reproduce:

1. Launch CCHMapClusterController Example iOS
2. Wait for map fully loaded
3. Tap "Reset"

Expected results:
Map is reloaded with the same number of annotations

Actual results:
The same number of annotations is added to the map, doubling the numbers displayed for the first time, 3x, 4x and so on, every time you tap "Reset".

![2014-10-27 18 03 12](https://cloud.githubusercontent.com/assets/803905/4792956/6c31caf0-5dea-11e4-8506-a3b5d24483f8.png)
![2014-10-27 18 03 02](https://cloud.githubusercontent.com/assets/803905/4792958/6ceee59a-5dea-11e4-85be-702e50909993.png)
![2014-10-27 18 02 55](https://cloud.githubusercontent.com/assets/803905/4792957/6ce35086-5dea-11e4-9b0d-bf96a5cb9e42.png)

**Comment by uknowmeright** [comment] 2016-03-08 21:15
This bug makes this library virtually unusable. Has there been a fix or at least a workaround for this yet?

**Comment by choefele** [comment] 2016-03-09 15:06
For me, this only happens when I quickly add and remove annotations at the same time to the clustering – which is a use case I don't have.

You can help by
- Creating a unit tests that reproduces this problem
- Provide a solution that avoids this issue

Looking forward to your contrinutions

**Comment by bhapca** [comment] 2016-03-14 14:32
I can reproduce it consistently on the simulator iOS 9.2 (13C75). It seems to be a problem with MKPointAnnotation, which gets added to the set of annotations without detecting duplicates. 

Overriding the hash and isEqual as I did in 539c98b seems to be fixing the problem.

**Comment by choefele** [comment] 2016-03-19 14:55
@bhapca Can you please let me know how to reproduce this issue? I'm running the sample app in this repo on Xcode 7.2.1/iPhone 6/iOS 9.2 and tap the reset button. Where does the crash occur for you?

**Comment by bhapca** [comment] 2016-03-21 08:02
@choefele, I'm not experiencing any crash, instead I'm getting the duplicate annotations discussed in this issue. The screenshots I included show how the annotations set double in size after 2 consecutive taps on the Reset button. They're screenshots of the debug session, stopped at breakpoint, not crashed, (look at the lldb prompt) which shows the issue. 

The steps to repro are the same as described by @grigorye at the beginning of this thread. Essentially launch the sample app, wait for the map to load, tap Reset, see how the number of annotations increase. Repeat tapping Reset, to see the number of annotations keeping growing.

**Comment by choefele** [comment] 2016-04-30 18:59
I believe this is fixed in 674ec5802b9b9d8abe706ffff251cd017eb8c868

**Closed by choefele** 2016-04-30 18:59 UTC
Labels: bug
